# Copyright (c) General Electric Company, 2023.  All rights reserved.
FROM ubuntu:22.04

ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy
ENV no_proxy=$no_proxy

RUN groupadd g01034722
RUN useradd dp116731 -g g01034722 -d /home/dp116731 -s /bin/bash

# install Python 3 and Pip 3
RUN apt-get -y update && apt-get install -y $buildDeps --no-install-recommends \
    && apt-get install -y python3 python3-pip \
    && pip install --upgrade pip && hash -r

# install needed dependencies for Python 3
RUN pip install flask pika boto3 requests junit-xml pytest-cov \
    && pip install --upgrade setuptools

# install SDK
ADD rt106GenericAdaptorSQS.py rt106GenericAdaptorAMQP.py rt106GenericAdaptorREST.py rt106SpecificAdaptorCode.py rt106SpecificAdaptorDefinitions.json entrypoint.sh testGenericAdaptorAPIs.py testGenericAdaptorAMQP.py /rt106/

# configure folder structures
RUN mkdir /rt106/input && mkdir /rt106/output && mkdir /rt106/test

# set permissions
RUN chmod a+x /rt106/entrypoint.sh

# set the working directory
WORKDIR /rt106

# establish the user
# create non-privileged user and group
RUN groupadd -r rt106 && useradd -r -g rt106 rt106 && chown -R rt106:rt106 /rt106
USER rt106:rt106


# configure the default port for an analytic, can be overridden in entrypoint
EXPOSE 7106

# entry point
CMD ["/rt106/entrypoint.sh"]

